<a href="https://colab.research.google.com/github/Ygorca125/Analise_Obesidade/blob/main/C%C3%B3pia_de_PowerBI_Traducao_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

# Carregar o arquivo
df = pd.read_csv('/content/Obesity.csv')

print(f"✅ Arquivo carregado com sucesso! {df.shape[0]} linhas e {df.shape[1]} colunas.")
df.head()

✅ Arquivo carregado com sucesso! 2111 linhas e 17 colunas.

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [2]:
# Renomear colunas para português
df = df.rename(columns={
    'Gender': 'Genero',
    'Age': 'Idade',
    'Height': 'Altura',
    'family_history': 'Histórico_Familiar',
    'FAVC': 'Alimentos_Caloricos',
    'FCVC': 'Come_Vegetais',
    'NCP': 'Qtd_Refeicoes',
    'CAEC': 'Come_Entre_Refeicao',
    'SMOKE': 'Fumante',
    'CH2O': 'Quanto_Agua',
    'SCC': 'Monitora_Calorias',
    'FAF': 'Freq_Exercicio',
    'TUE': 'Tempo_Tela',
    'CALC': 'Freq_Alcool',
    'MTRANS': 'Meio_Transporte',
    'Obesity': 'Nível_obesidade'
})

print("✅ Colunas renomeadas com sucesso!")
df.head()

✅ Colunas renomeadas com sucesso!

,Genero,Idade,Altura,Weight,Histórico_Familiar,Alimentos_Caloricos,Come_Vegetais,Qtd_Refeicoes,Come_Entre_Refeicao,Fumante,Quanto_Agua,Monitora_Calorias,Freq_Exercicio,Tempo_Tela,Freq_Alcool,Meio_Transporte,Nível_obesidade
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [3]:
# ====================== TRADUÇÃO DOS DADOS ======================

# Dicionários de tradução
traducao_sim_nao = {'yes': 'Sim', 'no': 'Não'}

traducao_frequencia = {
    'no': 'Não',
    'Sometimes': 'Às vezes',
    'Frequently': 'Frequentemente',
    'Always': 'Sempre'
}

# Aplicando traduções
df['Genero'] = df['Genero'].map({'Female': 'Feminino', 'Male': 'Masculino'})

df['Histórico_Familiar'] = df['Histórico_Familiar'].map(traducao_sim_nao)
df['Alimentos_Caloricos'] = df['Alimentos_Caloricos'].map(traducao_sim_nao)
df['Fumante'] = df['Fumante'].map(traducao_sim_nao)
df['Monitora_Calorias'] = df['Monitora_Calorias'].map(traducao_sim_nao)

df['Come_Entre_Refeicao'] = df['Come_Entre_Refeicao'].map(traducao_frequencia)
df['Freq_Alcool'] = df['Freq_Alcool'].map(traducao_frequencia)

# Mapeamentos numéricos
df['Qtd_Refeicoes'] = df['Qtd_Refeicoes'].map({1: '1 refeição', 2: '2 refeições',
                                                 3: '3 refeições', 4: '4 refeições ou mais'})

df['Come_Vegetais'] = df['Come_Vegetais'].map({1: 'Raramente', 2: 'Às vezes', 3: 'Sempre'})
df['Quanto_Agua'] = df['Quanto_Agua'].map({1: '< 1 L/dia', 2: '1-2 L/dia', 3: '> 2 L/dia'})
df['Freq_Exercicio'] = df['Freq_Exercicio'].map({0: 'Nenhuma', 1: '1-2x/semana',
                                                  2: '3-4x/semana', 3: '5x ou mais'})
df['Tempo_Tela'] = df['Tempo_Tela'].map({0: '0-2 horas/dia', 1: '3-5 horas/dia', 2: 'Mais de 5 horas/dia'})

df['Meio_Transporte'] = df['Meio_Transporte'].map({
    'Public_Transportation': 'Transporte Público',
    'Automobile': 'Carro',
    'Motorbike': 'Moto',
    'Bike': 'Bicicleta',
    'Walking': 'A pé'
})

df['Nível_obesidade'] = df['Nível_obesidade'].map({
    'Insufficient_Weight': 'Abaixo do Peso',
    'Normal_Weight': 'Peso Normal',
    'Overweight_Level_I': 'Sobrepeso Nível I',
    'Overweight_Level_II': 'Sobrepeso Nível II',
    'Obesity_Type_I': 'Obesidade Tipo I',
    'Obesity_Type_II': 'Obesidade Tipo II',
    'Obesity_Type_III': 'Obesidade Tipo III'
})

# Arredondar valores numéricos
df['Idade'] = df['Idade'].round(2)
df['Altura'] = df['Altura'].round(2)

# Criar faixa etária
def definir_faixa_etaria(idade):
    if idade < 18:
        return 'Adolescente (<=18)'
    elif idade <= 29:
        return 'Jovem (18-29)'
    elif idade <= 44:
        return 'Adulto (30-44)'
    elif idade <= 59:
        return 'Meia-idade (45-59)'
    else:
        return 'Idoso (60+)'

df['Faixa_etaria'] = df['Idade'].apply(definir_faixa_etaria)

# Salvar versão traduzida
df.to_csv('Obesity_Traduzido_PowerBI.csv', index=False, encoding='utf-8')

print("✅ Tradução concluída com sucesso!")
print(f"Arquivo salvo: 'Obesity_Traduzido_PowerBI.csv'")
df.head()

✅ Tradução concluída com sucesso!
Arquivo salvo: 'Obesity_Traduzido_PowerBI.csv'

,Genero,Idade,Altura,Weight,Histórico_Familiar,Alimentos_Caloricos,Come_Vegetais,Qtd_Refeicoes,Come_Entre_Refeicao,Fumante,Quanto_Agua,Monitora_Calorias,Freq_Exercicio,Tempo_Tela,Freq_Alcool,Meio_Transporte,Nível_obesidade,Faixa_etaria
0,Feminino,21.0,1.62,64.0,Sim,Não,Às vezes,3 refeições,Às vezes,Não,1-2 L/dia,Não,Nenhuma,3-5 horas/dia,Não,Transporte Público,Peso Normal,Jovem (18-29)
1,Feminino,21.0,1.52,56.0,Sim,Não,Sempre,3 refeições,Às vezes,Sim,> 2 L/dia,Sim,5x ou mais,0-2 horas/dia,Às vezes,Transporte Público,Peso Normal,Jovem (18-29)
2,Masculino,23.0,1.80,77.0,Sim,Não,Às vezes,3 refeições,Às vezes,Não,1-2 L/dia,Não,3-4x/semana,3-5 horas/dia,Frequentemente,Transporte Público,Peso Normal,Jovem (18-29)
3,Masculino,27.0,1.80,87.0,Não,Não,Sempre,3 refeições,Às vezes,Não,1-2 L/dia,Não,3-4x/semana,0-2 horas/dia,Frequentemente,A pé,Sobrepeso Nível I,Jovem (18-29)
4,Masculino,22.0,1.78,89.8,Não,Não,Às vezes,1 refeição,Às vezes,Não,1-2 L/dia,Não,Nenhuma,0-2 horas/dia,Às vezes,Transporte Público,Sobrepeso Nível II,Jovem (18-29)

In [4]:
# ====================== ANÁLISE - Tempo_Tela ======================

print("🔍 ANÁLISE DA COLUNA 'Tempo_Tela'")
print("=" * 55)

print(f"Total de registros: {len(df)}")
print(f"Valores nulos: {df['Tempo_Tela'].isna().sum()}")
print(f"Valores únicos: {df['Tempo_Tela'].nunique(dropna=False)}")

print("\n📊 Distribuição:")
print(df['Tempo_Tela'].value_counts(dropna=False))

# Verificar problemas
problemas = df[df['Tempo_Tela'].isna() | (df['Tempo_Tela'] == '')]
if len(problemas) > 0:
    print(f"\n⚠️  Encontradas {len(problemas)} linhas com problema:")
    display(problemas.head())
else:
    print("\n✅ Não foram encontrados valores nulos ou em branco.")

🔍 ANÁLISE DA COLUNA 'Tempo_Tela'
=======================================================
Total de registros: 2111
Valores nulos: 1153
Valores únicos: 4

📊 Distribuição:
Tempo_Tela
NaN                    1153
0-2 horas/dia           557
3-5 horas/dia           292
Mais de 5 horas/dia     109
Name: count, dtype: int64

⚠️  Encontradas 1153 linhas com problema:

,Genero,Idade,Altura,Weight,Histórico_Familiar,Alimentos_Caloricos,Come_Vegetais,Qtd_Refeicoes,Come_Entre_Refeicao,Fumante,Quanto_Agua,Monitora_Calorias,Freq_Exercicio,Tempo_Tela,Freq_Alcool,Meio_Transporte,Nível_obesidade,Faixa_etaria
500,Feminino,26.00,1.62,110.792630,Sim,Sim,Sempre,3 refeições,Às vezes,Não,NaN,Não,Nenhuma,NaN,Às vezes,Transporte Público,Obesidade Tipo III,Jovem (18-29)
501,Feminino,21.85,1.76,137.796884,Sim,Sim,Sempre,3 refeições,Às vezes,Não,NaN,Não,NaN,NaN,Às vezes,Transporte Público,Obesidade Tipo III,Jovem (18-29)
502,Feminino,21.90,1.84,165.057269,Sim,Sim,Sempre,3 refeições,Às vezes,Não,NaN,Não,NaN,NaN,Às vezes,Transporte Público,Obesidade Tipo III,Jovem (18-29)
503,Feminino,18.31,1.75,133.034410,Sim,Sim,Sempre,3 refeições,Às vezes,Não,NaN,Não,NaN,NaN,Às vezes,Transporte Público,Obesidade Tipo III,Jovem (18-29)
504,Feminino,26.00,1.63,111.485516,Sim,Sim,Sempre,3 refeições,Às vezes,Não,NaN,Não,Nenhuma,NaN,Às vezes,Transporte Público,Obesidade Tipo III,Jovem (18-29)